### ISSUE TITLE
Add Luxembourg

### ISSUE THREAD

**Issue by grischard** [OpenRailwayMap/railway-operators#1]
Should it be https://de.wikipedia.org/wiki/Administration_des_Chemins_de_Fer or https://de.wikipedia.org/wiki/Soci%C3%A9t%C3%A9_Nationale_des_Chemins_de_Fer_Luxembourgeois ?

**Comment by rurseekatze** [comment]
I would say that CFL is the railway infrastructure operator, they have some information on their website: http://www.cfl.lu/espaces/infrastructure/de/. The Administration des Chemins de Fer seems to be a goverment agency comparable to the German [EBA](https://de.wikipedia.org/wiki/Eisenbahn-Bundesamt).

**Comment by rurseekatze** [comment]
Thanks for your pull request!

Do you know any more railway operator companies in Luxembourg such as tram operators or museum railways?

**Comment by grischard** [comment]
Aha, yes! There's [Luxtram](https://en.wikipedia.org/wiki/Trams_in_Luxembourg#Contemporary_and_future_usage) for the tram with `operator=Luxtram`, and for museums there's at least the [Train 1900](http://minettpark.lu/eng/train-1900) and [the minieresbunn](http://minettpark.lu/eng/activites/6_the-mining-train-minieresbunn).
